import { type Metadata } from "next";
import { WalletCards, Info } from "lucide-react";

import { requireUser } from "@/server/auth/guards";
import { getModeNetwork } from "@/server/mode";
import { listCloudWallets } from "@/server/services/cloud-wallet-service";
import { PageHeader } from "@/components/shared/page-header";
import { EmptyState } from "@/components/shared/empty-state";
import { CloudWalletCreateDialog } from "@/features/cloud-wallets/components/cloud-wallet-create-dialog";
import { CloudWalletCard } from "@/features/cloud-wallets/components/cloud-wallet-card";

export const metadata: Metadata = { title: "Cloud Wallets — StellarHooks" };

export default async function CloudWalletsPage() {
  const user = await requireUser();
  const network = await getModeNetwork();
  const wallets = await listCloudWallets(user.id, network);

  return (
    <div className="space-y-6">
      <PageHeader
        title="Cloud Wallets"
        description="Create and manage custodial Stellar wallets directly in the app."
        action={<CloudWalletCreateDialog network={network} />}
      />

      <div className="flex items-start gap-2 rounded-lg border border-warning/40 bg-warning/10 p-3 text-sm">
        <Info className="mt-0.5 size-4 shrink-0 text-warning" />
        <p className="text-muted-foreground">
          These are custodial wallets — secret keys are generated by the app and stored
          encrypted. Back up your secret key when creating a wallet. Prefer testnet while
          evaluating.
        </p>
      </div>

      {wallets.length === 0 ? (
        <EmptyState
          icon={WalletCards}
          title="No cloud wallets yet"
          description="Create a Stellar wallet to hold a balance and send payments from the dashboard."
          action={<CloudWalletCreateDialog network={network} />}
        />
      ) : (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {wallets.map((wallet) => (
            <CloudWalletCard key={wallet.id} wallet={wallet} />
          ))}
        </div>
      )}
    </div>
  );
}
